### ISSUE TITLE
Implement (or create proposal for) interface in OP-stack to use off-chain DA

### ISSUE THREAD

**Issue by eelanagaraj** [celo-org/optimism#21]

**Comment by stackman27** [comment]
Can we do something that celestia did to add DA layer on OP stack ? 

Current OP stack 
- Rollup Node: Derives L2 chain from L1 blocks. The Rollup Node (L2) recieves L1 blocks, filters tx for data usually `callData` & derives L2 chain from that data. 

- op-batcher: Submits L2 sequenced txs into L1 for verification. Rollup Node & batcher work in parallel so that L2 data submitted by batcher is retrieved from L1 and also rollup node to derive L2 block.

What Celestia does and How it works with OP-Stack? 
- Enables any blockchain as DA layer. 
- OP-Stack already abstracts [L1Chain](https://github.com/celo-org/optimism/blob/celo1/op-node/rollup/driver/driver.go#L41-L44) and [L2Chain](https://github.com/celo-org/optimism/blob/celo1/op-node/rollup/driver/driver.go#L46C6-L50) interface in codebase, celestia models a new interface called the [DAConfig](https://github.com/celestiaorg/optimism/blob/celestia-develop/op-node/rollup/da_config.go#L11C1-L15) 
- using the DAConfig interface Celestia is able to read/write to blockchain running in their blockchain nodes (for EigenDA it will just be eth) 
- [Send Tx](https://github.com/celestiaorg/optimism/blob/78f9f2375221df9addb73c1f033bfefdb107aef0/op-service/txmgr/txmgr.go#L213): Responsible for creating and sending actual tx to Celestia and returns a reference. The reference is then submitted to L1 as `callData` 
- [Read Tx](https://github.com/celestiaorg/optimism/blob/78f9f2375221df9addb73c1f033bfefdb107aef0/op-node/rollup/derive/calldata_source.go#L128): returns the tx data from Celestia by using the frame reference retrieve from batch inbox `callData` 
- The light nodes only transmits the tx reference and look up Celestia whenever its necessary to get all tx data 

Do you think this is a possible path to explore with EigenNode DA? 

Celestia PR that uses it as DA for op-stack: https://github.com/celestiaorg/optimism/pull/3

Glossary: 
L1 = eth Chain 
reference = a link to where the tx lies in Celestia (this is what gets sent to L1 chain via `callData`) 
frame = lowest level of abstraction for data in Optimism
